### ISSUE TITLE
Finish the artist page

### ISSUE THREAD

**Issue by jerelmiller** [apollographql/spotify-showcase#29]
Much of the artist page is implemented, however there is still some missing functionality

```[tasklist]
### Tasks
* [ ] Top tracks should show whether they are liked by the user (i.e. the heart icon)
* [ ] Double clicking on a track should start playing that track
* [ ] Add context menu for the top tracks
* [ ] Add context menu for each album tile
* [ ] Add context menu for related artists
* [ ] Add the ability to follow/unfollow the artist
```
