### ISSUE TITLE
Implement the queue page

### ISSUE THREAD

**Issue by jerelmiller** [apollographql/spotify-showcase#30]
https://open.spotify.com/queue

Add the ability to view the user's queue.

```[tasklist]
### Tasks
- [x] Clicking the "queue" button in the playbar should highlight it as active
- [x] When on the queue page, clicking the queue button again should take you back to the previous page
- [x] The queue list should show the currently playing track
- [x] The queue list should show the next set of tracks in the queue
```

### Limitations:

Unfortunately the Spotify API makes it impossible to determine when a user has added an item to the queue via the "add to queue" button. In Spotify's UI, this shows up in its own "Next in queue" section since tracks added in this manner "interrupt" the current flow of songs (such as playing an album). We will only be able to show the "currently playing" and next set of tracks.
